# Generated by Django 4.2 on 2023-04-25 17:08

import ckeditor.fields
import common.upload_to_files
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1550, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=1550, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=1550, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=1550, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=2750, null=True, verbose_name='URL')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.news_main_img, verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.news_news_img, verbose_name='Фотография')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('created',),
            },
        ),
    ]
