# Generated by Django 4.2 on 2023-04-26 18:29

import common.upload_to_files
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='file',
            field=models.FileField(upload_to=common.upload_to_files.cooperation_files, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(upload_to=common.upload_to_files.document_files, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'webp'])], verbose_name='Файл'),
        ),
    ]
