# Generated by Django 4.2 on 2023-05-06 13:05

import ckeditor.fields
import common.upload_to_files
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cooperation_file_alter_documentfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalCooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=230, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=230, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=230, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=230, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.international_main_img, verbose_name='Фото')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Международное сотрудничество',
                'verbose_name_plural': 'Международные сотрудничество',
                'ordering': ('-created',),
            },
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='is_international',
        ),
        migrations.CreateModel(
            name='InternationalCooperationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.international_images, verbose_name='Фотография')),
                ('international', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.internationalcooperation')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
