# Generated by Django 4.2 on 2023-05-10 20:20

import common.upload_to_files
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_internationalcooperation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Учебный процесс',
                'verbose_name_plural': 'Учебные процессы',
            },
        ),
        migrations.AddField(
            model_name='internationalcooperation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=common.upload_to_files.international_pdf, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Договор (PDF)'),
        ),
        migrations.CreateModel(
            name='EduProcessFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file', models.FileField(upload_to=common.upload_to_files.edu_process_files, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'webp'])], verbose_name='Файл')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.eduprocess', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Файл учебного процесса',
                'verbose_name_plural': 'Файлы учебных процессов',
            },
        ),
    ]
