# Generated by Django 4.2 on 2023-04-25 17:08

import common.upload_to_files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваша электронная почта')),
                ('message', models.TextField(verbose_name='Ваше сообщение')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Recaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=common.upload_to_files.recaptcha_img, verbose_name='Изображение в Формате JPG 60X350')),
                ('answer', models.IntegerField(verbose_name='Ответ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ReCaptcha',
                'verbose_name_plural': 'ReCaptcha',
                'ordering': ('-created',),
            },
        ),
    ]
