# Generated by Django 4.2 on 2023-04-26 18:29

import common.upload_to_files
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaptcha',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.recaptcha_img, verbose_name='Изображение в Формате JPG 60X350'),
        ),
    ]
