# Generated by Django 4.2 on 2023-04-25 17:08

import ckeditor.fields
import common.upload_to_files
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Наименование')),
                ('title_ru', models.CharField(max_length=350, null=True, verbose_name='Наименование')),
                ('title_en', models.CharField(max_length=350, null=True, verbose_name='Наименование')),
                ('title_ky', models.CharField(max_length=350, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=450, null=True, verbose_name='URL')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('contract', models.CharField(max_length=50, verbose_name='Сумма контракта')),
                ('form_of_training', models.CharField(choices=[('full_time', 'Очный'), ('full_and_part', 'Очный/Заочный'), ('part_time', 'Заочный')], default='full_time', max_length=20, verbose_name='Форма обучение')),
                ('basis_learning', models.CharField(choices=[('contract', 'Контракт'), ('contract_budget', 'Контракт/Бюджет')], default='contract', max_length=100, verbose_name='Основа обучения')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.specialty_main_img, verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ('-created',),
            },
        ),
    ]
