FULL_TIME: str = 'full_time'
FULL_AND_PART: str = 'full_and_part'
PART_TIME: str = 'part_time'

CONTRACT: str = 'contract'
CONTRACT_BUDGET: str = 'contract_budget'

ACTIVATE: str = 'activate'
DEACTIVATE: str = 'deactivate'
KYRGYZSTAN: str = 'kyrgyzstan'
RUSSIA: str = 'russia'
KAZAKHSTAN: str = 'kazakhstan'
KOREAN: str = 'korean'
NOT_MARRIED_MEN: str = 'not_married_men'
MARRIED_MEN: str = 'married_men'
NOT_MARRIED_WOMEN: str = 'not_married_women'
MARRIED_WOMEN: str = 'married_women'
DIVORCED: str = 'divorced'
MEN: str = 'men'
WOMEN: str = 'women'
ENGLISH: str = 'english'
GERMAN: str = 'german'
COURSE_1: str = 'course_1'
COURSE_2: str = 'course_2'
COURSE_3: str = 'course_3'
COURSE_4: str = 'course_4'
