# Generated by Django 4.2 on 2023-04-25 17:08

import common.upload_to_files
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=100, null=True, verbose_name='Порядковый номер')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('sur_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(choices=[('men', 'Мужской'), ('women', 'Женский')], default='men', max_length=10, verbose_name='Пол')),
                ('date_of_birth', models.DateField(verbose_name='День рождения')),
                ('nationality', models.CharField(choices=[('kazakhstan', 'Кыргыз'), ('russia', 'Русский'), ('kazakhstan', 'Казах')], default='kazakhstan', max_length=10, verbose_name='Национальность')),
                ('marital_status', models.CharField(choices=[('not_married_men', 'не женат'), ('married_men', 'женат'), ('not_married_women', 'не замужем'), ('married_women', 'замужем'), ('divorced', 'разведен(а)')], default='not_married_men', max_length=25, verbose_name='Семейное положение')),
                ('goal', models.TextField(blank=True, null=True, verbose_name='Цель')),
                ('work_skills', models.TextField(verbose_name='Навыки работы')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=common.upload_to_files.employee_file, verbose_name='Фото сотрудника ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('short_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое название')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Имя группы')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('course', models.CharField(choices=[('course_1', '1-курс'), ('course_2', '2-курс'), ('course_3', '3-курс'), ('course_4', '4-курс')], default='1-course', max_length=10, verbose_name='Курс')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='specialty.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('course',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(verbose_name='Начальный год')),
                ('year_of_release', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыты работы',
                'ordering': ('start_year',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkillUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание по повышению квалификации')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Повышение квалификацию',
                'verbose_name_plural': 'Повышение квалификации',
                'ordering': ('year',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('kyrgyzstan', 'Кыргызский'), ('kazakhstan', 'Казахский'), ('russia', 'Русский'), ('english', 'Английский'), ('german', 'Немецкий')], max_length=10, verbose_name='Язык')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(verbose_name='Начальный год')),
                ('year_of_release', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('name', models.CharField(max_length=255, verbose_name='Название ВУЗа или СПО')),
                ('direction', models.CharField(max_length=255, verbose_name='Направление')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образовании',
                'ordering': ('start_year',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('award', models.CharField(max_length=255, verbose_name='Описание награды')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'ordering': ('year',),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resume', to='employee.position', verbose_name='Должность'),
        ),
    ]
