# Generated by Django 4.2 on 2023-06-06 05:17

import ckeditor.fields
import common.upload_to_files
from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeeducation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeelanguages',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeskillup',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeworkexperience',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='group',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='employee',
            name='description',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Резюме'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=common.upload_to_files.employee_file, verbose_name='Фото сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(choices=[('kyrgyzstan', 'Кыргыз'), ('russia', 'Русский'), ('kazakhstan', 'Казах')], default='kyrgyzstan', max_length=10, verbose_name='Национальность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sur_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.DeleteModel(
            name='EmployeeAwards',
        ),
        migrations.DeleteModel(
            name='EmployeeEducation',
        ),
        migrations.DeleteModel(
            name='EmployeeLanguages',
        ),
        migrations.DeleteModel(
            name='EmployeeSkillUp',
        ),
        migrations.DeleteModel(
            name='EmployeeWorkExperience',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
