# Generated by Django 4.2 on 2023-06-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employeeeducation_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(choices=[('kyrgyzstan', 'Кыргыз'), ('russia', 'Русский'), ('kazakhstan', 'Казах'), ('kazakhstan', 'Кореец')], default='kyrgyzstan', max_length=10, verbose_name='Национальность'),
        ),
    ]
