# Generated by Django 4.2 on 2023-10-27 07:03

import common.upload_to_files
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Национальность',
                'verbose_name_plural': 'Национальности',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nationality',
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.employee_file, verbose_name='Фото сотрудника'),
        ),
    ]
