# Generated by Django 4.2 on 2023-10-27 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_nationality_remove_employee_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employee.nationality', verbose_name='Национальность'),
            preserve_default=False,
        ),
    ]
