# Generated by Django 4.2 on 2023-06-06 05:17

import ckeditor.fields
import common.upload_to_files
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=100, null=True, verbose_name='Порядковый номер')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('sur_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(choices=[('men', 'Мужской'), ('women', 'Женский')], default='men', max_length=10, verbose_name='Пол')),
                ('date_of_birth', models.DateField(verbose_name='День рождения')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Резюме')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=common.upload_to_files.student_file, verbose_name='Фото студента')),
            ],
            options={
                'verbose_name': 'Студентский совет',
                'verbose_name_plural': 'Студентский совет',
                'ordering': ('number',),
            },
        ),
    ]
