# Generated by Django 4.2 on 2023-06-06 06:19

import ckeditor.fields
import common.upload_to_files
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.saejeon_image, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Студентская жизнь',
                'verbose_name_plural': 'Студентская жизнь',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='StudentLiveImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.saejeon_images, verbose_name='Фотография')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='student.studentlive')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('created',),
            },
        ),
    ]
