# Generated by Django 4.2 on 2024-02-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentcouncil_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentLive',
            new_name='SaeJeon',
        ),
        migrations.RenameModel(
            old_name='StudentLiveImages',
            new_name='SaeJeonImages',
        ),
        migrations.AlterModelOptions(
            name='saejeon',
            options={'ordering': ('-created',), 'verbose_name': 'Сокулук Сэджон', 'verbose_name_plural': 'Сокулук Сэджон'},
        ),
        migrations.RenameField(
            model_name='saejeonimages',
            old_name='live',
            new_name='saejeon',
        ),
    ]
